import express from "express";
import path from "path";
import { createServer as createViteServer } from "vite";
import { GoogleGenAI } from "@google/genai";
import dotenv from "dotenv";

dotenv.config();

async function startServer() {
  const app = express();
  const PORT = 3000;

  app.use(express.json());

  // Gemini API client initialization (lazy-loaded when needed, with clean check)
  let aiClient: GoogleGenAI | null = null;
  function getGeminiClient(): GoogleGenAI {
    if (!aiClient) {
      const apiKey = process.env.GEMINI_API_KEY;
      if (!apiKey || apiKey === "MY_GEMINI_API_KEY") {
        throw new Error("GEMINI_API_KEY is not configured or is using the placeholder. Please set it in your environment variables.");
      }
      aiClient = new GoogleGenAI({
        apiKey: apiKey,
        httpOptions: {
          headers: {
            "User-Agent": "aistudio-build",
          },
        },
      });
    }
    return aiClient;
  }

  // 1. API route: Gemini Diagnostics
  app.post("/api/diagnose", async (req, res) => {
    try {
      const { tenant, status, metrics, systemState } = req.body;
      
      const prompt = `Analyze the current DevOps telemetry state for our tenant "${tenant || 'Global Admin'}".
Environment status: ${status || 'Normal'}
Current Metrics:
- Cloudflare CDN requests: ${metrics?.requests || '0'}
- Cloudflare Bandwidth: ${metrics?.bandwidth || '0 GB'}
- GitHub Pipeline state: ${metrics?.pipelineState || 'Success'}
- Gemini API Daily Token Burn: ${metrics?.tokenBurn || '0'} tokens
- System Alerts: ${metrics?.activeAlerts || '0'} active

System state description: ${systemState || 'No descriptive errors.'}

Provide a concise, high-visibility, technical diagnostic report in markdown format. It should include:
1. **Critical Assessment**: A 2-sentence breakdown of system health.
2. **Root Cause Analysis**: If there are anomalies (like build failures, high traffic spikes, or heavy token usage), identify the likely cause.
3. **Recommended Remediation**: 2-3 specific, actionable DevOps/SRE operations to resolve or optimize this state.

Keep the language professional, SRE-oriented, and highly actionable. No fluff. Limit the response to 150 words.`;

      const ai = getGeminiClient();
      const response = await ai.models.generateContent({
        model: "gemini-3.6-flash",
        contents: prompt,
        config: {
          temperature: 0.7,
        }
      });

      res.json({ 
        success: true, 
        report: response.text || "No response generated by model.",
        modelUsed: "gemini-3.6-flash"
      });
    } catch (error: any) {
      console.error("Gemini diagnostics failed:", error.message);
      res.status(500).json({ 
        success: false, 
        error: error.message || "Failed to generate diagnostics",
        isMocked: true,
        report: `### ⚠️ Diagnostic Failure: Offline/Demo Mode Active

The local system could not complete the Live Gemini API call because the \`GEMINI_API_KEY\` is not set or is invalid.

#### **Simulated SRE Assessment**
- **Status**: Telemetry parser fallback engaged.
- **Root Cause**: Live connection to Google Gemini model registry failed.
- **Simulated Recovery Protocol**:
  1. Go to **Settings > Secrets** to ensure your Gemini API key is valid.
  2. Verify your Express proxy server \`/api/diagnose\` is reachable.
  3. Under normal parameters, this panel provides real-time model telemetry audits, automated token quota recommendations, and root-cause analysis of build crashes.`
      });
    }
  });

  // 2. API route: Webhook Dispatch Simulation
  app.post("/api/webhook/test", (req, res) => {
    const { tenant, eventType } = req.body;
    console.log(`[Webhook Simulation] Dispatched ${eventType} event for ${tenant}`);
    res.json({
      success: true,
      timestamp: new Date().toISOString(),
      delivered: true,
      targetUrl: "https://api.cloudflare.com/client/v4/webhooks",
      payload: {
        event: eventType,
        tenant: tenant,
        details: "Simulated SRE alert dispatched from PulseDeck Command Center"
      }
    });
  });

  // 3. API route: Cloudflare Cache Purge
  app.post("/api/cloudflare/purge", (req, res) => {
    const { zoneId, tenant, purgeAll, files } = req.body;
    console.log(`[Cloudflare Purge] Purge request received for Zone: ${zoneId}, Tenant: ${tenant}`);
    res.json({
      success: true,
      timestamp: new Date().toISOString(),
      zone: zoneId,
      purged: purgeAll ? "all_assets" : files,
      message: `Cache successfully purged for ${tenant || 'Global'}`
    });
  });

  // Vite middleware setup
  if (process.env.NODE_ENV !== "production") {
    const vite = await createViteServer({
      server: { middlewareMode: true },
      appType: "spa",
    });
    app.use(vite.middlewares);
  } else {
    const distPath = path.join(process.cwd(), "dist");
    app.use(express.static(distPath));
    app.get("*", (req, res) => {
      res.sendFile(path.join(distPath, "index.html"));
    });
  }

  app.listen(PORT, "0.0.0.0", () => {
    console.log(`PulseDeck Server listening on http://0.0.0.0:${PORT}`);
  });
}

startServer();
