import { TenantWorkspace, GlobalDashboardConfig, SystemEvent } from "../types";

export const DEFAULT_GLOBAL_CONFIG: GlobalDashboardConfig = {
  dashboardName: "PulseDeck",
  theme: "emerald",
  simulationMode: "normal",
  strictEnvOverride: false,
  alertWebhookUrl: "https://api.cloudflare.com/client/v4/webhooks/alerts",
};

export const DEFAULT_TENANTS: TenantWorkspace[] = [
  {
    id: "acme-commerce",
    name: "Acme Commerce",
    domain: "acme-shop.io",
    env: "Production",
    cloudflare: {
      zoneId: "cf-zone-acme-prod-01",
      apiToken: "••••••••••••••••••••••••••••••••",
      requestsToday: 35500,
      uniqueVisitors: 6390,
      bandwidthServedGb: 13.42,
      cacheHitRatio: 87.6,
      threatsBlocked: 45,
    },
    github: {
      repoOwner: "acme-labs",
      repoName: "acme-commerce-portal",
      accessToken: "••••••••••••••••••••••••••••••••",
      rateLimitRemaining: 4736,
      openPrs: 3,
      passRate: 87.5,
      latestActionRun: {
        name: "CI/CD Pipeline",
        status: "FAILED",
        branch: "main",
        commitSha: "8f3a9d2",
        duration: 142,
        trigger: "push",
        message: "feat(api): optimize response latency with edge caching strategy",
        timestamp: "2026-08-08T04:31:00Z",
      },
    },
    gemini: {
      apiKey: "••••••••••••••••••••••••••••••••",
      selectedModel: "gemini-3.6-flash",
      dailyTokenBudget: 500000,
      tokensToday: 581396,
      estCostToday: 0.11,
      autoTelemetry: true,
    },
    alertThresholds: {
      buildFailures: true,
      tokenSpikes: true,
      gatewayErrors: true,
    },
  },
  {
    id: "nova-ai",
    name: "Nova AI Platform",
    domain: "nova-assistant.ai",
    env: "Production",
    cloudflare: {
      zoneId: "cf-zone-nova-prod-02",
      apiToken: "••••••••••••••••••••••••••••••••",
      requestsToday: 46339,
      uniqueVisitors: 8341,
      bandwidthServedGb: 18.25,
      cacheHitRatio: 91.2,
      threatsBlocked: 12,
    },
    github: {
      repoOwner: "nova-intelligence",
      repoName: "nova-core-agent",
      accessToken: "••••••••••••••••••••••••••••••••",
      rateLimitRemaining: 4982,
      openPrs: 1,
      passRate: 98.2,
      latestActionRun: {
        name: "Lint & Build Agent",
        status: "SUCCESS",
        branch: "main",
        commitSha: "f4a1c0d",
        duration: 88,
        trigger: "push",
        message: "refactor(core): optimize memory footprint on recursive agent calls",
        timestamp: "2026-08-08T03:15:00Z",
      },
    },
    gemini: {
      apiKey: "••••••••••••••••••••••••••••••••",
      selectedModel: "gemini-3.1-pro-preview",
      dailyTokenBudget: 1000000,
      tokensToday: 521360,
      estCostToday: 0.65,
      autoTelemetry: true,
    },
    alertThresholds: {
      buildFailures: true,
      tokenSpikes: false,
      gatewayErrors: true,
    },
  },
  {
    id: "zenith-dashboard",
    name: "Zenith Cloud Dashboard",
    domain: "zenith-cloud.net",
    env: "Staging",
    cloudflare: {
      zoneId: "cf-zone-zenith-stg-03",
      apiToken: "••••••••••••••••••••••••••••••••",
      requestsToday: 27355,
      uniqueVisitors: 4923,
      bandwidthServedGb: 9.12,
      cacheHitRatio: 84.1,
      threatsBlocked: 8,
    },
    github: {
      repoOwner: "zenith-cloud-labs",
      repoName: "zenith-dashboard",
      accessToken: "••••••••••••••••••••••••••••••••",
      rateLimitRemaining: 4120,
      openPrs: 5,
      passRate: 92.4,
      latestActionRun: {
        name: "Deploy Staging Stacks",
        status: "SUCCESS",
        branch: "develop",
        commitSha: "e9b1c7f",
        duration: 110,
        trigger: "pull_request",
        message: "fix(ui): resolve container environment secret variable binding",
        timestamp: "2026-08-08T02:40:00Z",
      },
    },
    gemini: {
      apiKey: "••••••••••••••••••••••••••••••••",
      selectedModel: "gemini-3.6-flash",
      dailyTokenBudget: 750000,
      tokensToday: 576890,
      estCostToday: 0.12,
      autoTelemetry: false,
    },
    alertThresholds: {
      buildFailures: false,
      tokenSpikes: true,
      gatewayErrors: false,
    },
  },
];

export const INITIAL_EVENTS: SystemEvent[] = [
  {
    id: "evt-1",
    tenantId: "acme-commerce",
    tenantName: "Acme Commerce",
    type: "error",
    source: "GitHub",
    message: "GitHub Workflow: CI/CD Pipeline failed on feat(api): optimize response latency (main)",
    timeAgo: "12 minutes ago",
  },
  {
    id: "evt-2",
    tenantId: "acme-commerce",
    tenantName: "Acme Commerce",
    type: "success",
    source: "GitHub",
    message: "GitHub Workflow: Lint & Typecheck succeeded on fix(ci): resolve container secret binding",
    timeAgo: "1 hour ago",
  },
  {
    id: "evt-3",
    tenantId: "acme-commerce",
    tenantName: "Acme Commerce",
    type: "success",
    source: "GitHub",
    message: "GitHub Workflow: Security Vulnerability Audit passed for snyk-scan.yml",
    timeAgo: "5 hours ago",
  },
  {
    id: "evt-4",
    tenantId: "nova-ai",
    tenantName: "Nova AI Platform",
    type: "warning",
    source: "Gemini",
    message: "Gemini AI Engine: Daily token usage reached 116.3% of allocated budget",
    timeAgo: "1 hour ago",
  },
  {
    id: "evt-5",
    tenantId: "zenith-dashboard",
    tenantName: "Zenith Cloud Dashboard",
    type: "success",
    source: "Cloudflare",
    message: "Cloudflare CDN Cache Purge complete for Zone cf-zone-zenith-stg-03",
    timeAgo: "Yesterday",
  }
];
